language: python
python:
    - '2.7'

#command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls pep8
  - pip install .

#command to run tests
script:
  - pep8 pydefm
  - py.test pydefm

after_success:
  - coveralls
